apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.redis
  version: v1
  metadata:
      - name: redisHost
        value: myredishost
      - name: redisPassword
        value: "myredispassword"
      - name: actorStateStore
        value: "true" 
      - name: enableTLS
        value: "true"
      - name: keyPrefix
        value: none