apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  version: v1
  metadata:
   - name: redisHost
     value: myredishost
   - name: redisPassword
     value: "myredispassword"
   - name: actorStateStore
     value: "true" 
   - name: enableTLS
     value: "true"
   - name: keyPrefix
     value: none